main: it.minecube.flowgames.FlowGames
name: FlowGames
version: MineCube
authors: [crazyhoorse961, iAmGio]
depend: [PlaceholderAPI, WorldEdit]

commands:
  arena:
    usage: /[command] <args>
  setlobby:
    usage: /[command]